name: 'Deploy'

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Build installer
        uses: mikefarah/yq@v4.45.1
        with:
          cmd: |
            cd repo/com.vrcfury.installer
            chmod +x ../.github/workflows/build_unitypackage.sh
            ../.github/workflows/build_unitypackage.sh \
                ../../VRCFury-installer.unitypackage \
                Packages/com.vrcfury.installer
      - name: set NOW
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_ENV"
      - name: Release installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NOW }}
          files: 'VRCFury-installer.unitypackage'
